apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rhvw6lzaf-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rhvw6lzaf-dotnet-basic-gitops